apiVersion: v1
kind: Pod
metadata: 
  name: testpods
  namespace : usn
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo hello; sleep 5 ; done"]
    - name : c01
      image: httpd
      ports: 
        - containerPort: 80



kubectl apply usn -f 6.yaml
kubectl get pods --namespace usn
kubectl exec --namespace usn testpod -it -c c00 -- /bin/bash
apt update
apt install curl
curl localhost:80
exit
kubectl logs testpod –c c00 --namespace usn